# Generated by Django 6.0.6 on 2026-08-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_messanger', '0002_message_self_encrypted_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
    ]
